# Generated by Django 5.2.1 on 2025-05-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=60)),
                ('category', models.CharField(choices=[('Bills', 'Bills'), ('Shopping', 'Shopping'), ('Transportation', 'Transportation'), ('Lifestyle', 'Lifestyle'), ('Education', 'Education'), ('Groceries', 'Groceries'), ('Entertainment', 'Entertainment'), ('Personal Care', 'Personal Care'), ('General', 'General'), ('Dining Out', 'Dining Out')], max_length=60)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
