# Generated by Django 5.2.1 on 2025-05-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Bills', 'Bills'), ('Shopping', 'Shopping'), ('Transportation', 'Transportation'), ('Lifestyle', 'Lifestyle'), ('Education', 'Education'), ('Groceries', 'Groceries'), ('Entertainment', 'Entertainment'), ('Personal Care', 'Personal Care'), ('General', 'General'), ('Dining Out', 'Dining Out')], max_length=60)),
                ('maximum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('theme', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('target', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('theme', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='transactions',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
