# Generated by Django 5.2.1 on 2025-05-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_budget_pots_transactions_is_recurring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='transactions',
            field=models.ManyToManyField(to='core_app.transactions'),
        ),
    ]
