# Generated by Django 5.2.1 on 2025-05-25 07:04

import backend.user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_financeuser_groups_financeuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='financeuser',
            managers=[
                ('objects', backend.user.models.FinanceUserManager()),
            ],
        ),
    ]
